### ISSUE TITLE
Look for touchmove event in Javascript

### ISSUE THREAD

**Issue by ShAd0wInK** [ShAd0wInK/INFINITY#4]
Goal: move a section with the finger on mobile, like a mobile app

![aperçu](https://i.stack.imgur.com/8oB8a.gif)

**Comment by WebFaker** [comment]
Pretty hard duh ... ![bitmoji](https://render.bitstrips.com/v2/cpanel/4a148723-fbbf-4972-8e6e-120148c5a497-1a4b1474-2fba-4a72-a82c-d2ad1368f33b-v1.png?transparent=1&palette=1&width=246)
