### ISSUE TITLE
Create spacemodule.html, will be spacemodule.php

### ISSUE THREAD

**Issue by ShAd0wInK** [ShAd0wInK/INFINITY#47]
**Goal :**
- Create the default space module page

**Comment by WebFaker** [comment]
Pakompri ![bitmoji](https://render.bitstrips.com/v2/cpanel/c0871c38-0c27-4ae4-9196-389fa986867a-f2a69005-03db-455b-b918-18ad88c2cbd8-v1.png?transparent=1&palette=1&width=246)
